name: habit_tracker
description: A habit tracker app with Firebase and local preferences
publish_to: 'none' # Remove this if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  
  # State Management & Local Storage
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  table_calendar: ^3.0.9
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3


  # State management
  provider: ^6.1.2
  flutter_riverpod: ^2.4.10

  # UI Helpers
  google_fonts: ^6.2.1

  # Charts for progress visualization
  fl_chart: ^0.69.0

  # HTTP for quotes API
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login.png
    - assets/images/welcome.png
    - assets/images/icon1.jpg
    - assets/images/icon2.jpg
    - assets/images/icon3.jpg
    - assets/images/icon4.jpg
    - assets/images/icon5.jpg
